### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MobileMarketing** [widop/WidopGoogleAnalyticsBundle#20] opened 2013-06-03 07:06 UTC
I've followed all instructions, downloaded key and believe I've input the configuration correctly but I'm getting the following error when trying to execute 

$query = $this->container->get('widop_google_analytics.query');

"Failed to retrieve access token (invalid_grant)."

Setting up the client initially seems to work ok

$client = $this->container->get('widop_google_analytics.client'); 

doesn't cause any issues

Cheers,
Patrick

**Comment by egeloen** [comment] 2013-06-18 21:31
@MobileMarketing If you get an invalid grant from google means there is a configuration issue. This exception is thrown if the bundle does not get a valid access token in order to access the google analytics service.

Does the user linked to the certificate have a read access to the google analytics application?

**Comment by egeloen** [comment] 2013-09-05 08:33
Closing as this is a configuration issue.

**Closed as completed by egeloen** 2013-09-05 08:33 UTC

**Comment by kachkaev** [comment] 2013-11-01 00:15
Having the same thing. @MobileMarketing, have you sorted the problem out? What was the cause?

**Comment by kachkaev** [comment] 2013-11-01 00:45
Apparently I fixed it myself. My laptop's time was 5 minutes fast, and this caused OAuth to fail. Thanks to this answer on StackOverflow: http://stackoverflow.com/questions/11973162/google-analytics-api-oauth-exception-invalid-grant-with-service-account-same
